name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Adjust this to your project's Java version

    - name: Build and Test (Exclude API Tests)
      run: ./gradlew test --exclude-pattern '**/api/DroneApiInterfaceTest.java'
