name: Run Tests with VPN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create VPN Config
      run: |
        echo "host = vpngate.frankfurt-university.de" > vpn_config
        echo "port = 443" >> vpn_config
        echo "username = ${{ secrets.VPN_USERNAME }}" >> vpn_config
        echo "password = ${{ secrets.VPN_PASSWORD }}" >> vpn_config

    - name: Connect to VPN
      run: |
        sudo openfortivpn -c vpn_config

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set API Token
      run: echo "DRONE_API_KEY=${{ secrets.DRONE_API_KEY }}" >> $GITHUB_ENV

    - name: Build and Test
      env:
        DRONE_API_KEY: ${{ secrets.DRONE_API_KEY }}
      run: |
        ./gradlew build test # For Gradle projects
        # or
        mvn clean test # For Maven projects
