name: Run Tests with VPN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install FortiClient VPN
      run: sudo apt-get update && sudo apt-get install -y openfortivpn

    - name: Connect to VPN
      env:
        VPN_SERVER: ${{ secrets.VPN_SERVER }}
        VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      run: |
        sudo openfortivpn $VPN_SERVER -u $VPN_USERNAME -p $VPN_PASSWORD --trusted-cert <CERTIFICATE_HASH>


    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Update if you use a different Java version

    - name: Set API Token
      run: echo "DRONE_API_KEY=${{ secrets.DRONE_API_KEY }}" >> $GITHUB_ENV

    - name: Build and Test
      env:
        DRONE_API_KEY: ${{ secrets.DRONE_API_KEY }}
      run: |
        ./gradlew build test # For Gradle projects
        # or
        mvn clean test # For Maven projects
