name: Run Tests with VPN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up FortiClient VPN
      uses: M4hmoudAly/Forticlient-VPN@V1.0.0
      with:
        gateway: ${{ secrets.VPN_SERVER }}
        port: ${{ secrets.VPN_PORT }}
        username: ${{ secrets.VPN_USERNAME }}
        password: ${{ secrets.VPN_PASSWORD }}

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Adjust this to your project's Java version

    - name: Set API Token
      run: echo "DRONE_API_KEY=${{ secrets.DRONE_API_KEY }}" >> $GITHUB_ENV

    - name: Build and Test
      env:
        DRONE_API_KEY: ${{ secrets.DRONE_API_KEY }}
      run: ./gradlew build test # Adjust this to your build tool
