name: Run All JUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Update if you use a different Java version

    - name: Build and Test
      run: |
        ./gradlew build test # For Gradle projects
        # or
        mvn clean test # For Maven projects
